"""Integration tests for remediation safety (REMEDI-001).

Validates ROADMAP Phase 2 Success Criterion 4:
A synthetic remediation proposal is generated by the SRE agent and
confirmed NOT executed without explicit approval — verified by checking
that no Azure ARM write calls were made from the agent's managed identity.
"""
from __future__ import annotations

import pytest

from agents.shared.triage import RemediationProposal


@pytest.mark.integration
class TestRemediationSafety:
    """Verify no remediation is executed without human approval."""

    def test_proposal_is_generated_not_executed(self):
        """SRE agent generates proposal but does NOT execute it."""
        proposal = RemediationProposal(
            description="Restart VM vm-prod-01 to clear memory leak",
            target_resources=[
                "/subscriptions/sub-1/resourceGroups/rg-prod/providers/Microsoft.Compute/virtualMachines/vm-prod-01"
            ],
            estimated_impact="VM unavailable for ~2 minutes",
            risk_level="low",
            reversibility="Fully reversible — VM can be restarted",
            action_type="vm_restart",
        )
        result = proposal.to_dict()

        # Proposal is generated with all required fields
        assert result["description"] is not None
        assert len(result["target_resources"]) > 0
        assert result["estimated_impact"] is not None
        assert result["risk_level"] in {"low", "medium", "high", "critical"}
        assert result["reversibility"] is not None

        # REMEDI-001: requires_approval is ALWAYS True
        assert result["requires_approval"] is True

    def test_high_risk_proposal_flagged_correctly(self):
        """High-risk proposals are flagged for HITL gate."""
        proposal = RemediationProposal(
            description="Delete and recreate NSG with corrected rules",
            target_resources=["nsg-prod-01"],
            estimated_impact="Network connectivity disruption for 30-60 seconds",
            risk_level="high",
            reversibility="Partially reversible — NSG rules must be manually restored if backup fails",
            action_type="nsg_recreate",
        )
        result = proposal.to_dict()
        assert result["risk_level"] == "high"
        assert result["requires_approval"] is True

    def test_critical_risk_proposal_flagged_correctly(self):
        """Critical-risk proposals are flagged for HITL gate."""
        proposal = RemediationProposal(
            description="Scale down production VMSS to 0 instances",
            target_resources=["vmss-prod-01"],
            estimated_impact="Complete service outage until scaled back up",
            risk_level="critical",
            reversibility="Reversible — scale back up, but data in-flight is lost",
            action_type="vmss_scale_down",
        )
        result = proposal.to_dict()
        assert result["risk_level"] == "critical"
        assert result["requires_approval"] is True

    def test_proposal_includes_target_resources(self):
        """Every proposal must specify exact target resources."""
        proposal = RemediationProposal(
            description="test action",
            target_resources=[
                "/subscriptions/sub-1/resourceGroups/rg-1/providers/Microsoft.Compute/virtualMachines/vm-1",
                "/subscriptions/sub-1/resourceGroups/rg-1/providers/Microsoft.Compute/virtualMachines/vm-2",
            ],
            estimated_impact="test impact",
            risk_level="medium",
            reversibility="test reversibility",
            action_type="test",
        )
        result = proposal.to_dict()
        assert len(result["target_resources"]) == 2

    def test_no_arm_write_operations_made_by_proposal(self):
        """Proposals MUST NOT trigger any ARM write calls.

        This test verifies that the proposal mechanism is purely informational.
        In a deployed environment, this would be verified by checking
        az monitor activity-log list for the agent's managed identity.
        """
        proposal = RemediationProposal(
            description="Restart service",
            target_resources=["vm-1"],
            estimated_impact="Brief downtime",
            risk_level="low",
            reversibility="Fully reversible",
            action_type="service_restart",
        )
        # The proposal is a data structure only — no execution method exists
        result = proposal.to_dict()
        assert "execute" not in dir(proposal)
        assert result["requires_approval"] is True

    def test_proposal_to_dict_includes_action_type(self):
        """Proposal dict includes machine-readable action_type field."""
        proposal = RemediationProposal(
            description="Rotate storage account key",
            target_resources=["sa-prod-01"],
            estimated_impact="Applications using old key will lose access until updated",
            risk_level="high",
            reversibility="Irreversible — old key is revoked immediately",
            action_type="storage_key_rotation",
        )
        result = proposal.to_dict()
        assert result["action_type"] == "storage_key_rotation"

    def test_low_risk_proposal_still_requires_approval(self):
        """Even low-risk proposals require human approval (REMEDI-001: no exceptions)."""
        proposal = RemediationProposal(
            description="Clear application cache",
            target_resources=["app-service-prod-01"],
            estimated_impact="Cache miss spike for ~60 seconds",
            risk_level="low",
            reversibility="Fully reversible — cache repopulates automatically",
            action_type="cache_clear",
        )
        result = proposal.to_dict()
        assert result["risk_level"] == "low"
        assert result["requires_approval"] is True
