"""Seed script for compliance_mappings table (Phase 54).

Inserts 150+ rows mapping Defender assessments, Azure Policy definitions,
and Advisor recommendations to CIS v8, NIST 800-53 Rev 5, and ASB v3.

Run:
    DATABASE_URL=postgresql://... python scripts/seed-compliance-mappings.py
"""
from __future__ import annotations

import asyncio
import os

# ---------------------------------------------------------------------------
# Seed data — 150+ rows across 3 finding types
# ---------------------------------------------------------------------------

COMPLIANCE_MAPPINGS: list[dict] = [
    # ===========================================================================
    # DEFENDER ASSESSMENT MAPPINGS (~90 rows)
    # ===========================================================================

    # --- Network Security (ASB NS-1 through NS-10) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-nsg-subnet-0001",
        "display_name": "Subnets should be associated with a network security group",
        "description": "Network security groups (NSG) help protect your subnet from potential threats by filtering traffic to and from your subnet.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-rdp-internet-0002",
        "display_name": "Management ports of virtual machines should be protected with just-in-time network access control",
        "description": "Possible network just-in-time (JIT) access was detected by Microsoft Defender for Cloud.",
        "cis_control_id": "4.5",
        "cis_title": "Use Multifactor Authentication for All Administrative Access",
        "nist_control_id": "AC-17",
        "nist_title": "Remote Access",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-ddos-0003",
        "display_name": "Azure DDoS Protection Standard should be enabled",
        "description": "DDoS protection standard provides additional mitigation capabilities over the basic service tier.",
        "cis_control_id": "12.3",
        "cis_title": "Securely Manage Network Infrastructure",
        "nist_control_id": "SC-5",
        "nist_title": "Denial-of-Service Protection",
        "asb_control_id": "NS-5",
        "asb_title": "Deploy DDOS protection",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-waf-appgw-0004",
        "display_name": "Web Application Firewall (WAF) should be enabled for Application Gateway",
        "description": "Deploys Azure Web Application Firewall (WAF) in front of public facing web applications for additional inspection of incoming traffic.",
        "cis_control_id": "13.10",
        "cis_title": "Perform Application Layer Filtering",
        "nist_control_id": "SC-7(5)",
        "nist_title": "Boundary Protection - Deny by Default",
        "asb_control_id": "NS-6",
        "asb_title": "Deploy web application firewall",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-tls-func-0005",
        "display_name": "Function App should only be accessible over HTTPS",
        "description": "Using HTTPS ensures server/service authentication and protects data in transit from network layer eavesdropping attacks.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "NS-8",
        "asb_title": "Detect and disable insecure services and protocols",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-private-ep-kv-0006",
        "display_name": "Azure Key Vault should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-flow-logs-0007",
        "display_name": "Flow logs should be configured for every network security group",
        "description": "Audit for network security groups to verify if flow logs are configured.",
        "cis_control_id": "13.6",
        "cis_title": "Collect Network Traffic Flow Logs",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-tls-min-0008",
        "display_name": "App Service should use the latest TLS version",
        "description": "Upgrade to the latest TLS version to take advantage of security improvements.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "NS-8",
        "asb_title": "Detect and disable insecure services and protocols",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-private-ep-cosmos-0009",
        "display_name": "Azure Cosmos DB should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-open-ports-0010",
        "display_name": "Internet-facing virtual machines should be protected with network security groups",
        "description": "Protect your virtual machine from potential threats by restricting access to it with a network security group (NSG).",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },

    # --- Asset Management (ASB AM-1 through AM-5) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-defender-servers-0011",
        "display_name": "Microsoft Defender for servers should be enabled",
        "description": "Microsoft Defender for servers provides real-time threat protection for your server workloads.",
        "cis_control_id": "10.1",
        "cis_title": "Deploy and Maintain Anti-Malware Software",
        "nist_control_id": "SI-3",
        "nist_title": "Malicious Code Protection",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-defender-storage-0012",
        "display_name": "Microsoft Defender for Storage should be enabled",
        "description": "Defender for Storage detects unusual and potentially harmful attempts to access or exploit storage accounts.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-resource-tags-0013",
        "display_name": "A maximum of 3 owners should be designated for your subscription",
        "description": "It is recommended to designate up to 3 subscription owners in order to reduce the potential for breach by a compromised owner.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges to Dedicated Administrator Accounts",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "AM-1",
        "asb_title": "Track asset inventory and their risks",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-managed-disks-0014",
        "display_name": "Virtual machines should use managed disks",
        "description": "This policy audits virtual machines that do not use managed disk.",
        "cis_control_id": "3.1",
        "cis_title": "Establish and Maintain a Data Management Process",
        "nist_control_id": "CM-8",
        "nist_title": "System Component Inventory",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-arc-connected-0015",
        "display_name": "Arc-enabled servers should be monitored by Microsoft Defender for Cloud",
        "description": "Arc-enabled servers should have Defender for Cloud agents installed.",
        "cis_control_id": "10.1",
        "cis_title": "Deploy and Maintain Anti-Malware Software",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "AM-3",
        "asb_title": "Ensure security of asset lifecycle management",
        "severity": "High",
    },

    # --- Identity Management (ASB IM-1 through IM-9) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-mfa-owner-0016",
        "display_name": "MFA should be enabled on accounts with owner permissions on your subscription",
        "description": "Multi-factor authentication (MFA) should be enabled for all subscription accounts with owner permissions.",
        "cis_control_id": "6.5",
        "cis_title": "Require MFA for Administrative Access",
        "nist_control_id": "IA-2(1)",
        "nist_title": "Identification and Authentication - MFA",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-mfa-write-0017",
        "display_name": "MFA should be enabled on accounts with write permissions on your subscription",
        "description": "Multi-factor authentication (MFA) should be enabled for all subscription accounts with write permissions.",
        "cis_control_id": "6.5",
        "cis_title": "Require MFA for Administrative Access",
        "nist_control_id": "IA-2(1)",
        "nist_title": "Identification and Authentication - MFA",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-mfa-read-0018",
        "display_name": "MFA should be enabled on accounts with read permissions on your subscription",
        "description": "Multi-factor authentication (MFA) should be enabled for all subscription accounts with read permissions.",
        "cis_control_id": "6.5",
        "cis_title": "Require MFA for Administrative Access",
        "nist_control_id": "IA-2(1)",
        "nist_title": "Identification and Authentication - MFA",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-cond-access-0019",
        "display_name": "Conditional Access policies should be used for Azure AD",
        "description": "Enforce conditional access policies to require MFA for risky sign-ins.",
        "cis_control_id": "6.4",
        "cis_title": "Require MFA for Remote Network Access",
        "nist_control_id": "IA-2(11)",
        "nist_title": "Remote Access - Separate Device",
        "asb_control_id": "IM-7",
        "asb_title": "Eliminate unintended credential exposure",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-managed-id-0020",
        "display_name": "App Service apps should use managed identity",
        "description": "Using a managed identity for authentication eliminates the need to store credentials in code.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-2",
        "asb_title": "Protect identity and authentication systems",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-guest-accounts-0021",
        "display_name": "External accounts with owner permissions should be removed from your subscription",
        "description": "External accounts with owner permissions should be removed from your subscription.",
        "cis_control_id": "5.6",
        "cis_title": "Centralize Account Management",
        "nist_control_id": "AC-2",
        "nist_title": "Account Management",
        "asb_control_id": "IM-3",
        "asb_title": "Manage application identities securely and automatically",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-legacy-auth-0022",
        "display_name": "Accounts with owner permissions on Azure resources should be MFA enabled",
        "description": "Verify that MFA is enabled for accounts that can perform management operations.",
        "cis_control_id": "6.5",
        "cis_title": "Require MFA for Administrative Access",
        "nist_control_id": "IA-5",
        "nist_title": "Authenticator Management",
        "asb_control_id": "IM-4",
        "asb_title": "Authenticate server and services",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-pim-0023",
        "display_name": "Privileged Identity Management should be used to protect privileged accounts",
        "description": "Use Azure PIM to provide time-bound access to privileged roles.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6(5)",
        "nist_title": "Privileged Accounts",
        "asb_control_id": "IM-8",
        "asb_title": "Restrict the exposure of credential and secrets",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-aad-auth-sql-0024",
        "display_name": "SQL servers should use Azure Active Directory administrator",
        "description": "Audit provisioning of an Azure Active Directory administrator for SQL servers to enable AAD authentication.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },

    # --- Privileged Access (ASB PA-1 through PA-8) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-jit-vm-0025",
        "display_name": "Just-in-time network access control should be applied on virtual machines",
        "description": "Microsoft Defender for Cloud has identified some overly permissive inbound rules for management ports in your virtual machine's firewall.",
        "cis_control_id": "4.6",
        "cis_title": "Use Dedicated Workstations for All Administrative Tasks",
        "nist_control_id": "AC-17",
        "nist_title": "Remote Access",
        "asb_control_id": "PA-2",
        "asb_title": "Avoid standing access for user accounts and permissions",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-rbac-subscription-0026",
        "display_name": "Subscriptions should not grant management access via classic administrator types",
        "description": "Use role-based access control (RBAC) to manage access to Azure subscriptions.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-1",
        "asb_title": "Separate and limit highly privileged/administrative users",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-min-owners-0027",
        "display_name": "There should be more than one owner assigned to your subscription",
        "description": "It is recommended to designate more than one subscription owner in order to have administrator access redundancy.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-1",
        "asb_title": "Separate and limit highly privileged/administrative users",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-external-write-0028",
        "display_name": "External accounts with write permissions should be removed from your subscription",
        "description": "External accounts with write permissions should be removed from your subscription.",
        "cis_control_id": "5.6",
        "cis_title": "Centralize Account Management",
        "nist_control_id": "AC-2",
        "nist_title": "Account Management",
        "asb_control_id": "PA-3",
        "asb_title": "Manage lifecycle of identities and entitlements",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-deprecated-accounts-0029",
        "display_name": "Deprecated accounts with owner permissions should be removed from your subscription",
        "description": "Deprecated accounts should be removed from your subscriptions.",
        "cis_control_id": "5.3",
        "cis_title": "Disable Dormant Accounts",
        "nist_control_id": "AC-2(3)",
        "nist_title": "Disable Inactive Accounts",
        "asb_control_id": "PA-3",
        "asb_title": "Manage lifecycle of identities and entitlements",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-custom-rbac-0030",
        "display_name": "Audit usage of custom RBAC roles",
        "description": "Audit built-in roles such as 'Owner, Contributor, Reader' instead of custom RBAC roles.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-7",
        "asb_title": "Follow just enough administration (least privilege) principle",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-emergency-access-0031",
        "display_name": "Emergency access accounts should be in the Owners group",
        "description": "Ensure emergency access accounts are configured for break-glass scenarios.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6(5)",
        "nist_title": "Privileged Accounts",
        "asb_control_id": "PA-4",
        "asb_title": "Review and reconcile user access regularly",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-external-read-0032",
        "display_name": "External accounts with read permissions should be removed from your subscription",
        "description": "External accounts with read permissions should be removed from your subscriptions.",
        "cis_control_id": "5.6",
        "cis_title": "Centralize Account Management",
        "nist_control_id": "AC-2",
        "nist_title": "Account Management",
        "asb_control_id": "PA-3",
        "asb_title": "Manage lifecycle of identities and entitlements",
        "severity": "Medium",
    },

    # --- Data Protection (ASB DP-1 through DP-8) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-disk-encrypt-0033",
        "display_name": "Virtual machines should encrypt temp disks, caches, and data flows between Compute and Storage resources",
        "description": "By default, a virtual machine's OS and data disks are encrypted-at-rest using platform-managed keys.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-storage-https-0034",
        "display_name": "Secure transfer to storage accounts should be enabled",
        "description": "Audit requirement of Secure transfer in your storage account.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "DP-3",
        "asb_title": "Encrypt sensitive data in transit",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-kv-soft-delete-0035",
        "display_name": "Key vaults should have soft delete enabled",
        "description": "Deleting a key vault without soft delete enabled permanently deletes all secrets, keys, and certificates stored in the Key Vault.",
        "cis_control_id": "11.4",
        "cis_title": "Establish and Maintain an Isolated Instance of the Recovery Environment",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "DP-8",
        "asb_title": "Ensure security of key and certificate repository",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-kv-purge-protect-0036",
        "display_name": "Key vaults should have purge protection enabled",
        "description": "Malicious deletion of a key vault can lead to permanent data loss.",
        "cis_control_id": "11.4",
        "cis_title": "Establish and Maintain an Isolated Instance of the Recovery Environment",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "DP-8",
        "asb_title": "Ensure security of key and certificate repository",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-sql-tde-0037",
        "display_name": "Transparent Data Encryption on SQL databases should be enabled",
        "description": "Transparent data encryption should be enabled to protect data-at-rest and meet compliance requirements.",
        "cis_control_id": "3.5",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-storage-cmk-0038",
        "display_name": "Storage accounts should use customer-managed key for encryption",
        "description": "Secure your storage account with greater flexibility using customer-managed keys.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28(1)",
        "nist_title": "Cryptographic Protection",
        "asb_control_id": "DP-5",
        "asb_title": "Use customer-managed key option in data at rest encryption when required",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-storage-no-public-0039",
        "display_name": "Storage account public access should be disallowed",
        "description": "Anonymous public read access to a container and its blobs in Azure Blob storage is a convenient way to share data but may present security risks.",
        "cis_control_id": "3.3",
        "cis_title": "Configure Data Access Control Lists",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "DP-2",
        "asb_title": "Monitor anomalies and threats targeting sensitive data",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-kv-access-0040",
        "display_name": "Key Vault keys should have an expiration date",
        "description": "Cryptographic keys should have a defined expiration date and not be permanent.",
        "cis_control_id": "14.8",
        "cis_title": "Encrypt Sensitive Information in Transit",
        "nist_control_id": "IA-5(1)",
        "nist_title": "Authenticator Management - Password-Based",
        "asb_control_id": "DP-8",
        "asb_title": "Ensure security of key and certificate repository",
        "severity": "High",
    },

    # --- Logging & Threat Detection (ASB LT-1 through LT-7) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-audit-sql-0041",
        "display_name": "Auditing on SQL server should be enabled",
        "description": "Auditing on SQL Server tracks database events and writes them to an audit log in your Azure storage account.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-2",
        "nist_title": "Event Logging",
        "asb_control_id": "LT-3",
        "asb_title": "Enable logging for Azure network activities",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-activity-log-alerts-0042",
        "display_name": "Activity log alert should exist for specific operations",
        "description": "Monitoring for Create or Update Network Security Group Rules events gives insight into network access changes.",
        "cis_control_id": "8.11",
        "cis_title": "Conduct Audit Log Reviews",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-5",
        "asb_title": "Centralize security log management and analysis",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-defender-dns-0043",
        "display_name": "Microsoft Defender for DNS should be enabled",
        "description": "Microsoft Defender for DNS provides an additional layer of protection by monitoring DNS queries.",
        "cis_control_id": "8.1",
        "cis_title": "Establish and Maintain an Audit Log Management Process",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-defender-keyvault-0044",
        "display_name": "Microsoft Defender for Key Vault should be enabled",
        "description": "Microsoft Defender for Key Vault provides additional protection against threats to Azure Key Vault.",
        "cis_control_id": "8.1",
        "cis_title": "Establish and Maintain an Audit Log Management Process",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-diag-settings-0045",
        "display_name": "Azure Monitor log profile should collect logs for all regions",
        "description": "Azure Monitor should collect activity logs for all regions.",
        "cis_control_id": "8.5",
        "cis_title": "Collect Detailed Audit Logs",
        "nist_control_id": "AU-3",
        "nist_title": "Content of Audit Records",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-sentinel-0046",
        "display_name": "Azure Defender for SIEM integration should be configured",
        "description": "Security information and event management (SIEM) enables monitoring of cloud workloads.",
        "cis_control_id": "8.9",
        "cis_title": "Centralize Audit Logs",
        "nist_control_id": "AU-6",
        "nist_title": "Audit Record Review, Analysis, and Reporting",
        "asb_control_id": "LT-6",
        "asb_title": "Configure log storage retention",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-log-retention-0047",
        "display_name": "Audit log retention period should be set to at least one year",
        "description": "Configure Log Analytics workspace to retain data for at least 365 days.",
        "cis_control_id": "8.10",
        "cis_title": "Retain Audit Logs",
        "nist_control_id": "AU-11",
        "nist_title": "Audit Record Retention",
        "asb_control_id": "LT-6",
        "asb_title": "Configure log storage retention",
        "severity": "Medium",
    },

    # --- Incident Response (ASB IR-1 through IR-7) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-security-contact-0048",
        "display_name": "Subscriptions should have a contact email address for security issues",
        "description": "To ensure the relevant people in your organization are notified when there is a potential security breach.",
        "cis_control_id": "17.2",
        "cis_title": "Establish and Maintain Contact Information for Reporting Security Incidents",
        "nist_control_id": "IR-2",
        "nist_title": "Incident Response Training",
        "asb_control_id": "IR-2",
        "asb_title": "Preparation - setup incident notification",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-email-owner-0049",
        "display_name": "Email notification to subscription owners should be enabled in Defender for Cloud",
        "description": "Enable email notifications to subscription owners in Defender for Cloud settings.",
        "cis_control_id": "17.2",
        "cis_title": "Establish and Maintain Contact Information for Reporting Security Incidents",
        "nist_control_id": "IR-6",
        "nist_title": "Incident Reporting",
        "asb_control_id": "IR-2",
        "asb_title": "Preparation - setup incident notification",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-logic-app-alerts-0050",
        "display_name": "Automation workflow for security alerts should be configured",
        "description": "Automate remediation responses to security alerts using Logic Apps.",
        "cis_control_id": "17.3",
        "cis_title": "Establish and Maintain an Enterprise Process for Reporting Security Incidents",
        "nist_control_id": "IR-4",
        "nist_title": "Incident Handling",
        "asb_control_id": "IR-3",
        "asb_title": "Detection and analysis - create incidents based on high quality alerts",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-high-severity-alerts-0051",
        "display_name": "Email notification for high severity alerts should be enabled",
        "description": "Enable email notifications for high severity alerts in Defender for Cloud.",
        "cis_control_id": "17.2",
        "cis_title": "Establish and Maintain Contact Information for Reporting Security Incidents",
        "nist_control_id": "IR-6",
        "nist_title": "Incident Reporting",
        "asb_control_id": "IR-2",
        "asb_title": "Preparation - setup incident notification",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-incident-playbook-0052",
        "display_name": "Security incidents should trigger automated playbook execution",
        "description": "Configure automated incident response playbooks.",
        "cis_control_id": "17.7",
        "cis_title": "Run Tabletop Exercises",
        "nist_control_id": "IR-4(1)",
        "nist_title": "Automated Incident Handling Processes",
        "asb_control_id": "IR-5",
        "asb_title": "Detection and analysis - prioritize incidents",
        "severity": "Low",
    },

    # --- Posture & Vulnerability Management (ASB PV/VA-1 through VA-6) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-vuln-assess-vm-0053",
        "display_name": "A vulnerability assessment solution should be enabled on your virtual machines",
        "description": "Audits virtual machines to detect whether they are running a supported vulnerability assessment solution.",
        "cis_control_id": "7.1",
        "cis_title": "Establish and Maintain a Vulnerability Management Process",
        "nist_control_id": "RA-5",
        "nist_title": "Vulnerability Monitoring and Scanning",
        "asb_control_id": "PV-5",
        "asb_title": "Perform vulnerability assessments",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-vuln-sql-0054",
        "display_name": "SQL databases should have vulnerability assessment findings resolved",
        "description": "Vulnerability assessment scans your database for security vulnerabilities.",
        "cis_control_id": "7.2",
        "cis_title": "Establish and Maintain a Remediation Process",
        "nist_control_id": "RA-5(2)",
        "nist_title": "Update Vulnerabilities to be Scanned",
        "asb_control_id": "PV-6",
        "asb_title": "Rapidly and automatically remediate vulnerabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-system-updates-0055",
        "display_name": "System updates should be installed on your machines",
        "description": "Missing security system updates on your servers will be monitored.",
        "cis_control_id": "7.4",
        "cis_title": "Manage and Remediate Vulnerabilities",
        "nist_control_id": "SI-2",
        "nist_title": "Flaw Remediation",
        "asb_control_id": "PV-7",
        "asb_title": "Rapidly and automatically remediate vulnerabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-os-vulns-0056",
        "display_name": "Vulnerabilities in security configuration on your machines should be remediated",
        "description": "Servers which do not satisfy the configured baseline will be monitored.",
        "cis_control_id": "4.1",
        "cis_title": "Establish and Maintain a Secure Configuration Process",
        "nist_control_id": "CM-6",
        "nist_title": "Configuration Settings",
        "asb_control_id": "PV-4",
        "asb_title": "Audit and enforce secure configurations for compute resources",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-container-registry-vuln-0057",
        "display_name": "Container registry images should have vulnerability findings resolved",
        "description": "Container image vulnerability assessment scans your registry for security vulnerabilities.",
        "cis_control_id": "7.2",
        "cis_title": "Establish and Maintain a Remediation Process",
        "nist_control_id": "RA-5",
        "nist_title": "Vulnerability Monitoring and Scanning",
        "asb_control_id": "PV-5",
        "asb_title": "Perform vulnerability assessments",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-security-baseline-0058",
        "display_name": "Machines should be configured to periodically check for missing system updates",
        "description": "Ensure machines are configured to check for missing updates.",
        "cis_control_id": "7.3",
        "cis_title": "Perform Automated Operating System Patch Management",
        "nist_control_id": "SI-2",
        "nist_title": "Flaw Remediation",
        "asb_control_id": "PV-7",
        "asb_title": "Rapidly and automatically remediate vulnerabilities",
        "severity": "Medium",
    },

    # --- Endpoint Security (ASB ES-1 through ES-3) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-mde-vm-0059",
        "display_name": "Endpoint protection solution should be installed on virtual machine scale sets",
        "description": "Audit the existence and health of an endpoint protection solution on virtual machine scale sets.",
        "cis_control_id": "10.1",
        "cis_title": "Deploy and Maintain Anti-Malware Software",
        "nist_control_id": "SI-3",
        "nist_title": "Malicious Code Protection",
        "asb_control_id": "ES-1",
        "asb_title": "Use Endpoint Detection and Response (EDR)",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-antimalware-vm-0060",
        "display_name": "Monitor missing Endpoint Protection in Microsoft Defender for Cloud",
        "description": "Servers without an installed Endpoint Protection agent will be monitored.",
        "cis_control_id": "10.1",
        "cis_title": "Deploy and Maintain Anti-Malware Software",
        "nist_control_id": "SI-3",
        "nist_title": "Malicious Code Protection",
        "asb_control_id": "ES-2",
        "asb_title": "Use centrally managed modern anti-malware software",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-edr-arc-0061",
        "display_name": "Arc-enabled servers should have Microsoft Defender for Endpoint installed",
        "description": "Ensure Microsoft Defender for Endpoint is installed on all Arc-enabled servers.",
        "cis_control_id": "10.1",
        "cis_title": "Deploy and Maintain Anti-Malware Software",
        "nist_control_id": "SI-3",
        "nist_title": "Malicious Code Protection",
        "asb_control_id": "ES-1",
        "asb_title": "Use Endpoint Detection and Response (EDR)",
        "severity": "High",
    },

    # --- Backup & Recovery (ASB BR-1 through BR-4) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-backup-vm-0062",
        "display_name": "Azure Backup should be enabled for Virtual Machines",
        "description": "Protect your Azure Virtual Machines by enabling Azure Backup.",
        "cis_control_id": "11.1",
        "cis_title": "Establish and Maintain a Data Recovery Process",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "BR-1",
        "asb_title": "Ensure regular automated backups",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-storage-geo-redundant-0063",
        "display_name": "Geo-redundant storage should be enabled for Storage Accounts",
        "description": "Use geo-redundancy to create highly available applications.",
        "cis_control_id": "11.2",
        "cis_title": "Perform Automated Backups",
        "nist_control_id": "CP-9(3)",
        "nist_title": "Separate Storage for Critical Information",
        "asb_control_id": "BR-3",
        "asb_title": "Validate all backups including customer-managed keys",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-sql-backup-0064",
        "display_name": "Long-term geo-redundant backup should be enabled for SQL databases",
        "description": "This policy audits any Azure SQL Database with long-term geo-redundant backup not enabled.",
        "cis_control_id": "11.2",
        "cis_title": "Perform Automated Backups",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "BR-1",
        "asb_title": "Ensure regular automated backups",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-cosmos-backup-0065",
        "display_name": "Azure Cosmos DB accounts should use customer-managed keys to encrypt data at rest",
        "description": "Customer-managed keys provide backup encryption for Cosmos DB.",
        "cis_control_id": "11.3",
        "cis_title": "Protect Recovery Data",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "BR-4",
        "asb_title": "Mitigate risk of lost keys",
        "severity": "Low",
    },

    # --- DevOps Security (ASB DS-1 through DS-6) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-acr-admin-disabled-0066",
        "display_name": "Container registries should not allow unrestricted network access",
        "description": "Azure container registries by default accept connections over the internet from hosts on any network.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "DS-5",
        "asb_title": "Secure DevOps infrastructure",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-acr-no-public-0067",
        "display_name": "Container registries should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "DS-5",
        "asb_title": "Secure DevOps infrastructure",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-github-advanced-0068",
        "display_name": "GitHub repositories should have code scanning enabled",
        "description": "Enable code scanning to find security vulnerabilities in source code.",
        "cis_control_id": "16.2",
        "cis_title": "Establish and Maintain a Process to Accept and Address Software Vulnerabilities",
        "nist_control_id": "SA-11(1)",
        "nist_title": "Developer Security Testing and Evaluation",
        "asb_control_id": "DS-2",
        "asb_title": "Secure the software supply chain",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-secret-scanning-0069",
        "display_name": "GitHub repositories should have secret scanning enabled",
        "description": "Secret scanning in GitHub helps prevent the accidental inclusion of credential information.",
        "cis_control_id": "3.12",
        "cis_title": "Segment Data Processing and Storage Based on Sensitivity",
        "nist_control_id": "IA-5",
        "nist_title": "Authenticator Management",
        "asb_control_id": "DS-6",
        "asb_title": "Secure developers workstations",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-iac-scan-0070",
        "display_name": "IaC templates should be scanned for vulnerabilities",
        "description": "Scan infrastructure as code templates before deployment.",
        "cis_control_id": "4.1",
        "cis_title": "Establish and Maintain a Secure Configuration Process",
        "nist_control_id": "CM-6",
        "nist_title": "Configuration Settings",
        "asb_control_id": "DS-4",
        "asb_title": "Integrate static application security testing into DevOps pipeline",
        "severity": "Medium",
    },

    # --- Governance & Strategy (ASB GS-1 through GS-11) ---
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-defender-plan-0071",
        "display_name": "Microsoft cloud security benchmark should be applied",
        "description": "The Microsoft cloud security benchmark provides security guidance.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "PM-9",
        "nist_title": "Risk Management Strategy",
        "asb_control_id": "GS-1",
        "asb_title": "Align organization roles, responsibilities and accountabilities",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-policy-compliance-0072",
        "display_name": "Azure security policies should be configured",
        "description": "Configure Azure security policies to ensure compliance.",
        "cis_control_id": "1.2",
        "cis_title": "Address Unauthorized Assets",
        "nist_control_id": "PM-11",
        "nist_title": "Mission/Business Process Definition",
        "asb_control_id": "GS-2",
        "asb_title": "Define and implement enterprise segmentation/separation of duties strategy",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-advisor-score-0073",
        "display_name": "Azure Advisor recommendations should be resolved",
        "description": "Address Azure Advisor security recommendations to improve security posture.",
        "cis_control_id": "2.1",
        "cis_title": "Establish and Maintain a Software Inventory",
        "nist_control_id": "CA-7",
        "nist_title": "Continuous Monitoring",
        "asb_control_id": "GS-5",
        "asb_title": "Define and implement network security strategy",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-resource-locks-0074",
        "display_name": "Critical resources should be protected with resource locks",
        "description": "Apply resource locks to prevent accidental deletion of critical Azure resources.",
        "cis_control_id": "3.1",
        "cis_title": "Establish and Maintain a Data Management Process",
        "nist_control_id": "CM-3",
        "nist_title": "Configuration Change Control",
        "asb_control_id": "GS-3",
        "asb_title": "Define and implement data protection strategy",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-policy-initiatives-0075",
        "display_name": "Azure regulatory compliance initiatives should be assigned",
        "description": "Assign regulatory compliance initiatives such as CIS, NIST, or PCI DSS to your subscription.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "PM-9",
        "nist_title": "Risk Management Strategy",
        "asb_control_id": "GS-1",
        "asb_title": "Align organization roles, responsibilities and accountabilities",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-cost-alerts-0076",
        "display_name": "Budgets should be configured for subscriptions",
        "description": "Configure Azure Cost Management budgets to track and control spending.",
        "cis_control_id": "2.7",
        "cis_title": "Address Unauthorized Software",
        "nist_control_id": "PM-12",
        "nist_title": "Insider Threat Program",
        "asb_control_id": "GS-9",
        "asb_title": "Define and implement endpoint security strategy",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-tags-required-0077",
        "display_name": "Resources should have required tags for governance",
        "description": "Enforce tagging policies to ensure proper resource governance and cost allocation.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "CM-8",
        "nist_title": "System Component Inventory",
        "asb_control_id": "GS-1",
        "asb_title": "Align organization roles, responsibilities and accountabilities",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-azure-policy-0078",
        "display_name": "Azure Policy guest configuration extension should be installed",
        "description": "Azure Policy guest configuration extension enables in-guest policy evaluation on virtual machines.",
        "cis_control_id": "4.1",
        "cis_title": "Establish and Maintain a Secure Configuration Process",
        "nist_control_id": "CM-2",
        "nist_title": "Baseline Configuration",
        "asb_control_id": "GS-7",
        "asb_title": "Define and implement security posture management strategy",
        "severity": "Medium",
    },

    # More Defender assessments to hit 90 total
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-asc-recommendations-0079",
        "display_name": "Kubernetes Services should be upgraded to a non-vulnerable Kubernetes version",
        "description": "Upgrade your Kubernetes service cluster to a later Kubernetes version.",
        "cis_control_id": "7.4",
        "cis_title": "Manage and Remediate Vulnerabilities",
        "nist_control_id": "SI-2",
        "nist_title": "Flaw Remediation",
        "asb_control_id": "PV-7",
        "asb_title": "Rapidly and automatically remediate vulnerabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-aks-rbac-0080",
        "display_name": "Role-Based Access Control should be used on Kubernetes Services",
        "description": "Enable RBAC on Kubernetes to provide granular filtering on the actions users can perform.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-7",
        "asb_title": "Follow just enough administration (least privilege) principle",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-aks-authorized-ip-0081",
        "display_name": "Authorized IP ranges should be defined on Kubernetes Services",
        "description": "Restrict access to the Kubernetes Service Management API by granting API access only to IP addresses in specific ranges.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-app-insights-0082",
        "display_name": "Application Insights should be enabled for all App Services",
        "description": "Application Insights monitors web application availability, performance, and usage.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-service-health-alerts-0083",
        "display_name": "Service health alerts should be configured",
        "description": "Configure Azure Service Health alerts to receive notifications about service issues.",
        "cis_control_id": "17.4",
        "cis_title": "Establish and Maintain an Incident Response Process",
        "nist_control_id": "IR-4",
        "nist_title": "Incident Handling",
        "asb_control_id": "IR-2",
        "asb_title": "Preparation - setup incident notification",
        "severity": "Low",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-vm-password-0084",
        "display_name": "Virtual machines should use Azure AD authentication for Linux",
        "description": "Enable Azure Active Directory (Azure AD) login for Linux virtual machines.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-6",
        "asb_title": "Use strong authentication controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-sql-advanced-threat-0085",
        "display_name": "Advanced data security should be enabled on SQL Managed Instance",
        "description": "Audit each SQL Managed Instance without advanced data security.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-cosmos-fw-0086",
        "display_name": "Azure Cosmos DB accounts should have firewall rules",
        "description": "Firewall rules should be defined on your Azure Cosmos DB accounts to prevent traffic from unauthorized sources.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-func-app-auth-0087",
        "display_name": "Function apps should have authentication enabled",
        "description": "Azure App Service Authentication is a feature that can prevent anonymous HTTP requests from reaching the function app.",
        "cis_control_id": "6.2",
        "cis_title": "Establish an Access Revoking Process",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-6",
        "asb_title": "Use strong authentication controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-app-service-auth-0088",
        "display_name": "App Service apps should have authentication enabled",
        "description": "Azure App Service Authentication is a feature that can prevent anonymous HTTP requests.",
        "cis_control_id": "6.2",
        "cis_title": "Establish an Access Revoking Process",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-6",
        "asb_title": "Use strong authentication controls",
        "severity": "Medium",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-kv-expiry-secrets-0089",
        "display_name": "Key Vault secrets should have an expiration date",
        "description": "Secrets should have a defined expiration date and not be permanent.",
        "cis_control_id": "14.8",
        "cis_title": "Encrypt Sensitive Information in Transit",
        "nist_control_id": "IA-5(1)",
        "nist_title": "Authenticator Management - Password-Based",
        "asb_control_id": "DP-8",
        "asb_title": "Ensure security of key and certificate repository",
        "severity": "High",
    },
    {
        "finding_type": "defender_assessment",
        "defender_rule_id": "dabc-storage-blob-versioning-0090",
        "display_name": "Blob storage containers in storage accounts should have versioning enabled",
        "description": "Blob versioning enables automatic storage of prior versions of a blob.",
        "cis_control_id": "11.2",
        "cis_title": "Perform Automated Backups",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "BR-1",
        "asb_title": "Ensure regular automated backups",
        "severity": "Low",
    },

    # ===========================================================================
    # AZURE POLICY MAPPINGS (~40 rows)
    # ===========================================================================
    {
        "finding_type": "policy",
        "defender_rule_id": "Allowed locations",
        "display_name": "Allowed locations policy",
        "description": "This policy enables you to restrict the locations your organization can specify when deploying resources.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "CM-2",
        "nist_title": "Baseline Configuration",
        "asb_control_id": "GS-2",
        "asb_title": "Define and implement enterprise segmentation/separation of duties strategy",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Storage accounts should use private link",
        "display_name": "Storage accounts should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Kubernetes clusters should use internal load balancers",
        "display_name": "Kubernetes clusters should use internal load balancers",
        "description": "Use an internal load balancer to make a Kubernetes service accessible only to applications running in the same virtual network.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "SQL databases should have vulnerability assessment configured",
        "display_name": "SQL databases should have vulnerability assessment configured",
        "description": "Audit Azure SQL servers which do not have recurring vulnerability assessment scans configured.",
        "cis_control_id": "7.1",
        "cis_title": "Establish and Maintain a Vulnerability Management Process",
        "nist_control_id": "RA-5",
        "nist_title": "Vulnerability Monitoring and Scanning",
        "asb_control_id": "PV-5",
        "asb_title": "Perform vulnerability assessments",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Network Watcher should be enabled",
        "display_name": "Network Watcher should be enabled",
        "description": "Network Watcher is a regional service that enables you to monitor and diagnose conditions at a network level.",
        "cis_control_id": "13.6",
        "cis_title": "Collect Network Traffic Flow Logs",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-3",
        "asb_title": "Enable logging for Azure network activities",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure subscriptions should have a log profile for Activity Log",
        "display_name": "Azure subscriptions should have a log profile for Activity Log",
        "description": "This policy ensures that a log profile is created for exporting activity logs.",
        "cis_control_id": "8.5",
        "cis_title": "Collect Detailed Audit Logs",
        "nist_control_id": "AU-3",
        "nist_title": "Content of Audit Records",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Diagnostic logs in Azure Data Lake Storage should be enabled",
        "display_name": "Diagnostic logs in Azure Data Lake Storage should be enabled",
        "description": "Enabling diagnostic logs helps audit activity trails.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-2",
        "nist_title": "Event Logging",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "SQL Server Threat Detection types should include ALL",
        "display_name": "SQL Server Threat Detection types should include ALL",
        "description": "Enable all SQL Advanced Threat Detection types.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Email notifications to subscription owners should be enabled in Advanced Threat Protection settings",
        "display_name": "Email notifications to subscription owners should be enabled in Advanced Threat Protection settings",
        "description": "Ensure email notifications are sent to subscription owners for Advanced Threat Protection.",
        "cis_control_id": "17.2",
        "cis_title": "Establish and Maintain Contact Information for Reporting Security Incidents",
        "nist_control_id": "IR-6",
        "nist_title": "Incident Reporting",
        "asb_control_id": "IR-2",
        "asb_title": "Preparation - setup incident notification",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Automation account variables should be encrypted",
        "display_name": "Automation account variables should be encrypted",
        "description": "Variables in Automation accounts should be encrypted to protect sensitive data.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Service Bus Namespaces should disable public network access",
        "display_name": "Service Bus Namespaces should disable public network access",
        "description": "Disable public network access for Service Bus namespaces.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Event Hub Namespaces should disable public network access",
        "display_name": "Event Hub Namespaces should disable public network access",
        "description": "Disable public network access for Event Hub namespaces.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure SQL Database should have Azure Defender enabled",
        "display_name": "Azure SQL Database should have Azure Defender enabled",
        "description": "Azure Defender for SQL provides functionality for surfacing and mitigating potential database vulnerabilities.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Latest TLS version should be used for App Service",
        "display_name": "Latest TLS version should be used for App Service",
        "description": "Upgrade App Service to the latest TLS version.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "NS-8",
        "asb_title": "Detect and disable insecure services and protocols",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "CORS should not allow every resource to access your Function Apps",
        "display_name": "CORS should not allow every resource to access your Function Apps",
        "description": "Cross-Origin Resource Sharing (CORS) should not allow all domains to access your function app.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Redis Cache should use private link",
        "display_name": "Redis Cache should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "PostgreSQL flexible server should have Microsoft Entra Only Authentication enabled",
        "display_name": "PostgreSQL flexible server should have Microsoft Entra Only Authentication enabled",
        "description": "Disabling local authentication methods improves security for PostgreSQL servers.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "API Management services should use a virtual network",
        "display_name": "API Management services should use a virtual network",
        "description": "Deploy API Management in a virtual network to isolate it from public internet.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Managed identity should be used in your Function App",
        "display_name": "Managed identity should be used in your Function App",
        "description": "Managed identity for enhanced authentication security in Function Apps.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-2",
        "asb_title": "Protect identity and authentication systems",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "App Service should only be accessible over HTTPS",
        "display_name": "App Service should only be accessible over HTTPS",
        "description": "Using HTTPS ensures server/service authentication and protects data in transit.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "NS-8",
        "asb_title": "Detect and disable insecure services and protocols",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Web Application Firewall (WAF) should be enabled for Azure Front Door Service",
        "display_name": "Web Application Firewall (WAF) should be enabled for Azure Front Door Service",
        "description": "Deploy Azure Web Application Firewall in front of public facing web applications.",
        "cis_control_id": "13.10",
        "cis_title": "Perform Application Layer Filtering",
        "nist_control_id": "SC-7(5)",
        "nist_title": "Boundary Protection - Deny by Default",
        "asb_control_id": "NS-6",
        "asb_title": "Deploy web application firewall",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Container App environments should use network injection",
        "display_name": "Container App environments should use network injection",
        "description": "Container App environments should be deployed with virtual network injection enabled.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Resource logs in Key Vault should be enabled",
        "display_name": "Resource logs in Key Vault should be enabled",
        "description": "Audit enabling of resource logs. This enables you to recreate activity trails to use for investigation.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-2",
        "nist_title": "Event Logging",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Storage accounts should have the specified minimum TLS version",
        "display_name": "Storage accounts should have the specified minimum TLS version",
        "description": "Configure a minimum TLS version for storage accounts.",
        "cis_control_id": "14.4",
        "cis_title": "Encrypt All Sensitive Information in Transit",
        "nist_control_id": "SC-8",
        "nist_title": "Transmission Confidentiality and Integrity",
        "asb_control_id": "NS-8",
        "asb_title": "Detect and disable insecure services and protocols",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Container registries should not allow unrestricted network access",
        "display_name": "Container registries should not allow unrestricted network access",
        "description": "Azure container registries by default accept connections over the internet from hosts on any network.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Virtual machines should be migrated to new Azure Resource Manager resources",
        "display_name": "Virtual machines should be migrated to new Azure Resource Manager resources",
        "description": "Use the new Azure Resource Manager for your virtual machines.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "CM-8",
        "nist_title": "System Component Inventory",
        "asb_control_id": "AM-1",
        "asb_title": "Track asset inventory and their risks",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Public network access should be disabled for MySQL flexible servers",
        "display_name": "Public network access should be disabled for MySQL flexible servers",
        "description": "Disabling public network access property improves security by ensuring your Azure Database for MySQL flexible server.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Public IP addresses should not be associated to virtual machine network interfaces",
        "display_name": "Public IP addresses should not be associated to virtual machine network interfaces",
        "description": "This policy denies network interfaces configured with any public IP.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure AD should be enabled for Azure Kubernetes Service Clusters",
        "display_name": "Azure AD should be enabled for Azure Kubernetes Service Clusters",
        "description": "Integrate Azure Active Directory with AKS clusters.",
        "cis_control_id": "5.1",
        "cis_title": "Establish and Maintain an Inventory of Accounts",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Disk encryption should be applied on virtual machines",
        "display_name": "Disk encryption should be applied on virtual machines",
        "description": "Virtual machines without an enabled disk encryption will be monitored.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Subnets should be associated with a Network Security Group",
        "display_name": "Subnets should be associated with a Network Security Group",
        "description": "Protect your subnet from potential threats by restricting access to it with a Network Security Group (NSG).",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Log Analytics agent should be installed on virtual machine scale sets for Azure Security Center monitoring",
        "display_name": "Log Analytics agent should be installed on virtual machine scale sets",
        "description": "Install the Log Analytics agent on virtual machine scale sets.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure container registry admin account should be disabled",
        "display_name": "Azure container registry admin account should be disabled",
        "description": "The admin account of Azure Container Registry is designed for a single user for development and test purposes.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-1",
        "asb_title": "Separate and limit highly privileged/administrative users",
        "severity": "Medium",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure Event Grid domains should use private link",
        "display_name": "Azure Event Grid domains should use private link",
        "description": "Azure Private Link lets you connect your virtual network to Azure services without a public IP address.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Deploy export to Event Hub for Microsoft Defender for Cloud data",
        "display_name": "Deploy export to Event Hub for Microsoft Defender for Cloud data",
        "description": "Enable export to Event Hub for Microsoft Defender for Cloud data.",
        "cis_control_id": "8.9",
        "cis_title": "Centralize Audit Logs",
        "nist_control_id": "AU-6",
        "nist_title": "Audit Record Review, Analysis, and Reporting",
        "asb_control_id": "LT-5",
        "asb_title": "Centralize security log management and analysis",
        "severity": "Low",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Windows virtual machines should enable Azure Disk Encryption or EncryptionAtHost",
        "display_name": "Windows virtual machines should enable Azure Disk Encryption or EncryptionAtHost",
        "description": "By default, a virtual machine's OS and data disks are encrypted-at-rest using platform-managed keys.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Guest accounts with write permissions on Azure resources should be removed",
        "display_name": "Guest accounts with write permissions on Azure resources should be removed",
        "description": "External accounts with write permissions should be removed from your subscription.",
        "cis_control_id": "5.6",
        "cis_title": "Centralize Account Management",
        "nist_control_id": "AC-2",
        "nist_title": "Account Management",
        "asb_control_id": "PA-3",
        "asb_title": "Manage lifecycle of identities and entitlements",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "A maximum of 3 owners should be designated for your subscription",
        "display_name": "A maximum of 3 owners should be designated for your subscription (policy)",
        "description": "Restrict the number of subscription owners to reduce breach risk.",
        "cis_control_id": "5.4",
        "cis_title": "Restrict Administrator Privileges",
        "nist_control_id": "AC-6",
        "nist_title": "Least Privilege",
        "asb_control_id": "PA-1",
        "asb_title": "Separate and limit highly privileged/administrative users",
        "severity": "High",
    },
    {
        "finding_type": "policy",
        "defender_rule_id": "Azure Machine Learning Workspaces should disable public network access",
        "display_name": "Azure Machine Learning Workspaces should disable public network access",
        "description": "Disable public network access for ML workspaces.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-2",
        "asb_title": "Secure cloud services with network controls",
        "severity": "Medium",
    },

    # ===========================================================================
    # ADVISOR SECURITY RECOMMENDATION MAPPINGS (~20 rows)
    # ===========================================================================
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Azure DDoS Protection Standard",
        "display_name": "Enable Azure DDoS Protection Standard",
        "description": "Azure DDoS Protection Standard provides additional DDoS mitigation capabilities.",
        "cis_control_id": "12.3",
        "cis_title": "Securely Manage Network Infrastructure",
        "nist_control_id": "SC-5",
        "nist_title": "Denial-of-Service Protection",
        "asb_control_id": "NS-5",
        "asb_title": "Deploy DDOS protection",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Use managed disks for VMs",
        "display_name": "Use managed disks for VMs",
        "description": "Managed disks provide better reliability and security for virtual machines.",
        "cis_control_id": "3.1",
        "cis_title": "Establish and Maintain a Data Management Process",
        "nist_control_id": "CM-8",
        "nist_title": "System Component Inventory",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "Low",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable soft delete for Azure Blob Storage",
        "display_name": "Enable soft delete for Azure Blob Storage",
        "description": "Enabling soft delete for blob storage helps recover data from accidental deletion.",
        "cis_control_id": "11.1",
        "cis_title": "Establish and Maintain a Data Recovery Process",
        "nist_control_id": "CP-9",
        "nist_title": "System Backup",
        "asb_control_id": "BR-1",
        "asb_title": "Ensure regular automated backups",
        "severity": "Low",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Azure Security Center alerts",
        "display_name": "Enable Azure Security Center alerts",
        "description": "Enable security alerts in Microsoft Defender for Cloud.",
        "cis_control_id": "8.1",
        "cis_title": "Establish and Maintain an Audit Log Management Process",
        "nist_control_id": "IR-4",
        "nist_title": "Incident Handling",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Apply disk encryption to virtual machine disks",
        "display_name": "Apply disk encryption to virtual machine disks",
        "description": "Encrypt virtual machine disks to protect data at rest.",
        "cis_control_id": "3.6",
        "cis_title": "Encrypt Data on End-User Devices",
        "nist_control_id": "SC-28",
        "nist_title": "Protection of Information at Rest",
        "asb_control_id": "DP-4",
        "asb_title": "Enable data at rest encryption by default",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable multi-factor authentication for Azure subscriptions",
        "display_name": "Enable multi-factor authentication for Azure subscriptions",
        "description": "Enable MFA for all Azure subscription accounts.",
        "cis_control_id": "6.5",
        "cis_title": "Require MFA for Administrative Access",
        "nist_control_id": "IA-2(1)",
        "nist_title": "Identification and Authentication - MFA",
        "asb_control_id": "IM-1",
        "asb_title": "Standardize Azure Active Directory as the central identity",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Restrict access to Azure Key Vault",
        "display_name": "Restrict access to Azure Key Vault",
        "description": "Restrict public network access to Key Vault.",
        "cis_control_id": "12.7",
        "cis_title": "Manage Access Control for Remote Assets",
        "nist_control_id": "AC-4",
        "nist_title": "Information Flow Enforcement",
        "asb_control_id": "DP-8",
        "asb_title": "Ensure security of key and certificate repository",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Configure activity log alerts",
        "display_name": "Configure activity log alerts",
        "description": "Activity log alerts provide notifications for important events.",
        "cis_control_id": "8.11",
        "cis_title": "Conduct Audit Log Reviews",
        "nist_control_id": "AU-6",
        "nist_title": "Audit Record Review, Analysis, and Reporting",
        "asb_control_id": "LT-5",
        "asb_title": "Centralize security log management and analysis",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Upgrade storage accounts to Azure Resource Manager",
        "display_name": "Upgrade storage accounts to Azure Resource Manager",
        "description": "Migrate classic storage accounts to Azure Resource Manager.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "CM-8",
        "nist_title": "System Component Inventory",
        "asb_control_id": "AM-1",
        "asb_title": "Track asset inventory and their risks",
        "severity": "Low",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Advanced Threat Protection for Azure SQL",
        "display_name": "Enable Advanced Threat Protection for Azure SQL",
        "description": "Advanced Threat Protection detects anomalous database activities.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "LT-1",
        "asb_title": "Enable threat detection capabilities",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Just-In-Time VM access",
        "display_name": "Enable Just-In-Time VM access",
        "description": "JIT access reduces the attack surface by enabling access to VMs only when needed.",
        "cis_control_id": "4.5",
        "cis_title": "Use Multifactor Authentication for All Administrative Access",
        "nist_control_id": "AC-17",
        "nist_title": "Remote Access",
        "asb_control_id": "PA-2",
        "asb_title": "Avoid standing access for user accounts and permissions",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable adaptive network hardening",
        "display_name": "Enable adaptive network hardening",
        "description": "Adaptive network hardening further hardens NSG rules by analyzing traffic patterns.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable vulnerability assessment on SQL servers",
        "display_name": "Enable vulnerability assessment on SQL servers",
        "description": "Enable vulnerability assessment scanning on SQL servers.",
        "cis_control_id": "7.1",
        "cis_title": "Establish and Maintain a Vulnerability Management Process",
        "nist_control_id": "RA-5",
        "nist_title": "Vulnerability Monitoring and Scanning",
        "asb_control_id": "PV-5",
        "asb_title": "Perform vulnerability assessments",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Azure Firewall for VNets with sensitive workloads",
        "display_name": "Enable Azure Firewall for VNets with sensitive workloads",
        "description": "Azure Firewall provides network-level protection for virtual networks.",
        "cis_control_id": "12.4",
        "cis_title": "Establish and Maintain Architecture Diagram(s)",
        "nist_control_id": "SC-7",
        "nist_title": "Boundary Protection",
        "asb_control_id": "NS-4",
        "asb_title": "Deploy intrusion detection/intrusion prevention systems",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Implement network segmentation",
        "display_name": "Implement network segmentation",
        "description": "Segment your network to limit the potential impact of a security breach.",
        "cis_control_id": "12.2",
        "cis_title": "Establish and Maintain a Secure Network Architecture",
        "nist_control_id": "SC-7(5)",
        "nist_title": "Boundary Protection - Deny by Default",
        "asb_control_id": "NS-1",
        "asb_title": "Establish network segmentation boundaries",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Rotate service principal credentials regularly",
        "display_name": "Rotate service principal credentials regularly",
        "description": "Regularly rotate service principal client secrets to reduce security risk.",
        "cis_control_id": "5.2",
        "cis_title": "Use Unique Passwords",
        "nist_control_id": "IA-5(1)",
        "nist_title": "Authenticator Management - Password-Based",
        "asb_control_id": "IM-7",
        "asb_title": "Eliminate unintended credential exposure",
        "severity": "Medium",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Use Azure Policy to enforce compliance",
        "display_name": "Use Azure Policy to enforce compliance",
        "description": "Assign Azure Policy initiatives to track and enforce compliance.",
        "cis_control_id": "1.1",
        "cis_title": "Establish and Maintain Detailed Enterprise Asset Inventory",
        "nist_control_id": "PM-9",
        "nist_title": "Risk Management Strategy",
        "asb_control_id": "GS-1",
        "asb_title": "Align organization roles, responsibilities and accountabilities",
        "severity": "Low",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Security Center standard tier",
        "display_name": "Enable Security Center standard tier",
        "description": "Enable the Microsoft Defender for Cloud standard tier for enhanced threat protection.",
        "cis_control_id": "10.5",
        "cis_title": "Enable Anti-Exploitation Features",
        "nist_control_id": "SI-4",
        "nist_title": "System Monitoring",
        "asb_control_id": "AM-2",
        "asb_title": "Use only approved applications",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Review and restrict legacy authentication protocols",
        "display_name": "Review and restrict legacy authentication protocols",
        "description": "Block legacy authentication protocols that bypass MFA.",
        "cis_control_id": "6.4",
        "cis_title": "Require MFA for Remote Network Access",
        "nist_control_id": "IA-2",
        "nist_title": "Identification and Authentication",
        "asb_control_id": "IM-6",
        "asb_title": "Use strong authentication controls",
        "severity": "High",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Configure resource group deletion locks for production",
        "display_name": "Configure resource group deletion locks for production",
        "description": "Use Azure resource locks to prevent accidental deletion of production resource groups.",
        "cis_control_id": "3.1",
        "cis_title": "Establish and Maintain a Data Management Process",
        "nist_control_id": "CM-3",
        "nist_title": "Configuration Change Control",
        "asb_control_id": "GS-3",
        "asb_title": "Define and implement data protection strategy",
        "severity": "Low",
    },
    {
        "finding_type": "advisor",
        "defender_rule_id": "Enable Azure Monitor for virtual machines",
        "display_name": "Enable Azure Monitor for virtual machines",
        "description": "Azure Monitor for VMs provides health and performance monitoring for virtual machines.",
        "cis_control_id": "8.2",
        "cis_title": "Collect Audit Logs",
        "nist_control_id": "AU-12",
        "nist_title": "Audit Record Generation",
        "asb_control_id": "LT-4",
        "asb_title": "Enable logging for Azure resources",
        "severity": "Low",
    },
]

# ---------------------------------------------------------------------------
# Database operations
# ---------------------------------------------------------------------------

INSERT_SQL = """
INSERT INTO compliance_mappings
    (finding_type, defender_rule_id, display_name, description,
     cis_control_id, cis_title, nist_control_id, nist_title,
     asb_control_id, asb_title, severity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT DO NOTHING
"""


async def main() -> None:
    """Run migration and insert seed data."""
    import asyncpg  # noqa: PLC0415

    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL environment variable not set.")

    conn = await asyncpg.connect(database_url)
    try:
        # Run the migration first (idempotent)
        import sys  # noqa: PLC0415
        sys.path.insert(0, "services/api-gateway")
        from migrations._004_create_compliance_mappings import up as run_migration  # type: ignore[import]
        await run_migration(conn)
        print("Migration applied (or already current).")

        # Insert seed rows
        inserted = 0
        for row in COMPLIANCE_MAPPINGS:
            await conn.execute(
                INSERT_SQL,
                row["finding_type"],
                row.get("defender_rule_id"),
                row["display_name"],
                row.get("description"),
                row.get("cis_control_id"),
                row.get("cis_title"),
                row.get("nist_control_id"),
                row.get("nist_title"),
                row.get("asb_control_id"),
                row.get("asb_title"),
                row.get("severity", "Medium"),
            )
            inserted += 1

        print(f"Seeded {inserted} compliance mappings.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
